esphome:
  name: caliper

esp8266:
  board: d1_mini

api:
ota:
  port: 3232
wifi:
  ssid: <wifi_ssid>
  password: <wifi_password>
logger:

captive_portal:

external_components:
  - source:
      type: local
      path: components

sensor:
  - platform: caliper
    name: Caliper